---

- connection: local
  gather_facts: false
  hosts: firewall
  
  collections:
    - paloaltonetworks.panos
  
  tasks:
  - name: Get system info
    paloaltonetworks.panos.panos_op:
        provider: '{{ device }}'
        cmd: 'show system info'
    register: changes

  - name: print changes
    debug:
     var: output.stdout_lines
