---

- hosts: firewall
  connection: local
  gather_facts: true

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
  collections:
    - paloaltonetworks.panos

 
 # roles:
 # - role: PaloAltoNetworks.paloaltonetworks
 
  tasks:
  - name: Get system info
    panos_op:
      provider: '{{ device }}'
      cmd: 'show high-availability state'
    register: info 


  - debug:
      msg: '{{ info.stdout }}'
