---

- connection: local
  gather_facts: true
  hosts: firewall

  collections:
    - paloaltonetworks.panos

 
 # roles:
 # - role: PaloAltoNetworks.paloaltonetworks
 
  tasks:
  - name: Get system info
    panos_op:
 #     provider: '{{ provider }}'
      cmd: 'show high-availability state'
    register: info 


  - debug:
      msg: '{{ info.stdout }}'
