---


- name: Network Getting Started with first Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: ios
  
 
  tasks: 
  - name: Display interface brief
    ios_command:
      commands: show ip int brief
    register: output
   
  - name: print output
    debug:
     var: output.stdout_lines
     
