---


- name: Nexus int
  connection: ansible.netcommon.network_cli
  network_os: cisco.nxos.nxos
  gather_facts: false
  hosts: nexus
  
 
  tasks: 
  - name: Display interface brief
    nxos_command:
      commands: show ip int brief vrf all
    register: output
   
  - name: print output
    debug:
     var: output.stdout_lines
